### PR TITLE
Fix: lower macos target

### PR DESCRIPTION
**Pull request by Tuditi**
# Description of change

Lowers macOS target for nodejs bindings and covector release. I also updated the node version to use 16.

## Links to any relevant issues

https://github.com/iotaledger/firefly/issues/4766

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Thoralf-M — COMMENTED** [review]
In your original PR you also changed it in `.github/workflows/release-python-bindings.yml`, is there a reason to not do that now?

**Review by thibault-martinez — CHANGES_REQUESTED** [review]
```
        warning: rocksdb/cache/clock_cache.cc:135:14: error: aligned allocation function of type 'void *(std::size_t, std::align_val_t)' is only available on macOS 10.14 or newer
        warning:       array_(new HandleImpl[size_t{1} << length_bits_]) {
```

**Comment by rajivshah3** [comment]
> ```
> 
>         warning: rocksdb/cache/clock_cache.cc:135:14: error: aligned allocation function of type 'void *(std::size_t, std::align_val_t)' is only available on macOS 10.14 or newer
> 
>         warning:       array_(new HandleImpl[size_t{1} << length_bits_]) {
> 
> ```

I think we may need to make a PR to rust-rocksdb to fix this since we need to add the `-faligned-new` flag

**Comment by Tuditi** [comment]
> In your original PR you also changed it in `.github/workflows/release-python-bindings.yml`, is there a reason to not do that now?

I omitted that change, since the check for python bindings was failing and we do not need it for Firefly. Although I just realized it also fails without that change. I will look into it

**Comment by thibault-martinez** [comment]
> > In your original PR you also changed it in `.github/workflows/release-python-bindings.yml`, is there a reason to not do that now?
> 
> I omitted that change, since the check for python bindings was failing and we do not need it for Firefly. Although I just realized it also fails without that change. I will look into it

Did you have a chance to took at it?

**Comment by Tuditi** [comment]
> > > In your original PR you also changed it in `.github/workflows/release-python-bindings.yml`, is there a reason to not do that now?
> > 
> > 
> > I omitted that change, since the check for python bindings was failing and we do not need it for Firefly. Although I just realized it also fails without that change. I will look into it
> 
> Did you have a chance to took at it?

Not yet, will have some focus time on Friday the latest.

**Review by thibault-martinez — APPROVED** [review]

**Review by Thoralf-M — APPROVED** [review]

**Review by kwek20 — APPROVED** [review]

**Pull request merged**
